<a href="https://colab.research.google.com/github/vishalkumar182/c-100-days-challenge/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Learning numpy

import numpy as np
array_1d = np.array([1,2,3,4,5]) ## Note: list is passed as a argument to the array() fxn.
print(array_1d)

[1 2 3 4 5]


In [ ]:
array_2d = np.array([[1,2,3],[4,5,6]])  # array inside an array [ [], [], [],.......[] ] n dimensional array
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
# array_2d = np.array([1,2,3],[4,5,6]) error bcoz it treat it as a two array
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
# ===========================
# np.array() Syntax
# ===========================

# Syntax:
# np.array(object, dtype=None)

# object = Jis data se NumPy array banana hai. (Required)
# dtype  = Kis data type (int, float, str, etc.) me store karna hai. (Optional)

# object me kya-kya de sakte hain?

# 1. List (1D Array)
# [1, 2, 3]

# 2. Tuple (1D Array)
# (1, 2, 3)

# 3. List of Lists (2D Array)
# [[1, 2, 3],
#  [4, 5, 6]]

# 4. List of Tuples
# [(1, 2), (3, 4)]

# 5. Tuple of Lists
# ([1, 2], [3, 4])

# Simple Rule:
# object = "Jis data ko NumPy Array me convert karna hai."

# Example:
arr_1d= np.array([1, 2, 3])        # 1D Array
arr_2d = np.array([[1,2],[3,4]])    # 2D Array
arr_tuple = np.array((1,2,3))          # Tuple -> Array
arr = np.array([1,2,3], dtype=float)  # int -> float
print(f"Float Array: {arr}, 1D Array: {arr_1d}, 2D Array: {arr_2d}, Tuple Array: {arr_tuple}")

Float Array: [1. 2. 3.], 1D Array: [1 2 3], 2D Array: [[1 2]
 [3 4]], Tuple Array: [1 2 3]
